---
server:
  host: localhost
  port: 2101
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
postgres:
  host: localhost
  port: 5432
  username: postgres
  database: authentication_identity_user_mgmt
  application: authentication_identity_user_mgmt
  connectTimeoutSeconds: 5
  sslMode: disable
