---
server:
  host: localhost
  port: 2102
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
postgres:
  host: localhost
  port: 5432
  username: postgres
  database: access_control_roles_permissions
  application: access_control_roles_permissions
  connectTimeoutSeconds: 5
  sslMode: disable