---
server:
  host: localhost
  port: 2101
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
postgres:
  host: localhost
  port: 5432
  username: postgres
  database: authentication
  application: authentication
  connectTimeoutSeconds: 5
  sslMode: disable
ui_app:
  urls:
    login: http://localhost:2150/login
    register: http://localhost:2150/register
